/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.femass.gui;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.femass.dao.AutorDao;
import org.femass.dao.LivroDao;
import org.femass.model.Autor;
import org.femass.model.Livro;

/**
 *
 * @author enzoappi
 */
public class GuiAutorLivro extends javax.swing.JDialog {
    private Livro livro; //criando o atributo de livro
    
    /**
     * Creates new form GuiLivroAutor
     */
    public GuiAutorLivro(java.awt.Frame parent, boolean modal, Livro livro) {
        super(parent, modal);
        initComponents();
        this.livro = livro;
        lblLivro.setText("Livro: " + this.livro.getNome()); //fazer aparecer o nome do livro na parte superior da tela
        try {
            lstAutoresDisponiveis.setListData(new AutorDao().getLista().toArray()); //pegar a lista de autores e inserindo na lista de Disponíveis.
            lstAutoresLivro.setListData(this.livro.getAutores().toArray()); //preenchendo a lista de autores do livro.
        } catch (SQLException ex) {
            Logger.getLogger(GuiAutorLivro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstAutoresDisponiveis = new javax.swing.JList();
        lblAutoresDisponiveis = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstAutoresLivro = new javax.swing.JList();
        lblAutoresLivro = new javax.swing.JLabel();
        lblLivro = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Autores do Livro");

        jScrollPane1.setViewportView(lstAutoresDisponiveis);

        lblAutoresDisponiveis.setText("Autores Disponíveis");

        jScrollPane2.setViewportView(lstAutoresLivro);

        lblAutoresLivro.setText("Autores do Livro");

        lblLivro.setText("Livro");

        btnAdicionar.setText(">");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnRemover.setText("<");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAdicionar)
                            .addComponent(btnRemover)))
                    .addComponent(lblAutoresDisponiveis)
                    .addComponent(lblLivro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblAutoresLivro)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblLivro)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutoresDisponiveis)
                    .addComponent(lblAutoresLivro))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnAdicionar)
                        .addGap(49, 49, 49)
                        .addComponent(btnRemover)
                        .addContainerGap(133, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        Autor autor = (Autor) lstAutoresDisponiveis.getSelectedValue(); //pegar um autor selecionado na lista de autores disponiveis
        this.livro.adicionarAutor(autor); //adicionar autor a lista de autores do livro.
        try {
            new LivroDao().alterar(this.livro);
        } catch (SQLException ex) {
            Logger.getLogger(GuiAutorLivro.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
        lstAutoresLivro.setListData(this.livro.getAutores().toArray());
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        Autor autor = (Autor) lstAutoresLivro.getSelectedValue(); //peguei o valor selecionado entre os autores do livro, na lista
        this.livro.removerAutor(autor);
        try {
            new LivroDao().alterar(this.livro);
        } catch (SQLException ex) {
            Logger.getLogger(GuiAutorLivro.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
        lstAutoresLivro.setListData(this.livro.getAutores().toArray());
    }//GEN-LAST:event_btnRemoverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAutoresDisponiveis;
    private javax.swing.JLabel lblAutoresLivro;
    private javax.swing.JLabel lblLivro;
    private javax.swing.JList lstAutoresDisponiveis;
    private javax.swing.JList lstAutoresLivro;
    // End of variables declaration//GEN-END:variables
}
