/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.femass.gui;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.femass.dao.EmprestimoDao;
import org.femass.dao.LeitorDao;
import org.femass.dao.LivroDao;
import org.femass.model.Emprestimo;
import org.femass.model.Leitor;
import org.femass.model.Livro;

/**
 *
 * @author enzoappi
 */
public class GuiEmprestimo extends javax.swing.JInternalFrame {
    private static boolean janelaAberta = false; //criou-se um atributo statico para usarmos no controle das aberturas de janela
    
    public static GuiEmprestimo abrir() { //metodo statico que sera utilizado para o controle de abertura da janbela de autores
        if(!janelaAberta) {
            GuiEmprestimo gE = new GuiEmprestimo(); 
            janelaAberta = true;
            return gE;
        } else {
            return null;
        }
    }
    /**
     * Creates new form GuiEmprestimo
     */
    private GuiEmprestimo() {
        initComponents();
        try {
            List<Livro> livros = new LivroDao().getListaDisponivel();
            cboLivros.removeAllItems();
            for(Livro livro: livros) {
                cboLivros.addItem(livro);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GuiEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            List<Leitor> leitores = new LeitorDao().getLista();
            cboLeitores.removeAllItems();
            for(Leitor leitor: leitores) {
                cboLeitores.addItem(leitor);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GuiEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEmprestar = new javax.swing.JButton();
        cboLivros = new javax.swing.JComboBox();
        cboLeitores = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Livro");

        jLabel2.setText("Leitor");

        btnEmprestar.setText("Emprestar");
        btnEmprestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboLivros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboLeitores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 224, Short.MAX_VALUE)
                        .addComponent(btnEmprestar)))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboLivros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboLeitores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEmprestar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestarActionPerformed
        // TODO add your handling code here:
        Emprestimo emprestimo =  new Emprestimo();
        emprestimo.setLeitor((Leitor) cboLeitores.getSelectedItem());
        emprestimo.setLivro((Livro) cboLivros.getSelectedItem());
        emprestimo.setFinalizado(false);
        try {
            new EmprestimoDao().gravar(emprestimo);
        } catch (SQLException ex) {
            Logger.getLogger(GuiEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
        janelaAberta = false;
        this.setVisible(false);
    }//GEN-LAST:event_btnEmprestarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        janelaAberta = false;
    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmprestar;
    private javax.swing.JComboBox cboLeitores;
    private javax.swing.JComboBox cboLivros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
