/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.LeitorDao;
import javax.swing.JOptionPane;
import model.Aluno;
import model.Endereco;
import model.Leitor;
import model.Professor;
import model.TipoLeitor;
import model.TipoLogradouro;
import model.Uf;

/**
 *
 * @author enzoappi
 */
public class GuiCadastroLeitor extends javax.swing.JFrame {
//    private Aluno aluno;
//    private Professor professor;
    /**
     * Creates new form GuiPessoa
     */
    public GuiCadastroLeitor() {
        initComponents();
        preencherCombo();
    }

    private void preencherCombo() {
        for(TipoLeitor tLt: TipoLeitor.values()) {
            cboTipoLeitor.addItem(tLt);
        }
        
        for(TipoLogradouro tLg: TipoLogradouro.values()) {
            cboTipoLogradouro.addItem(tLg);
        }
        
        for(Uf uf: Uf.values()) {
            cboUf.addItem(uf);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblNomeLeitor = new javax.swing.JLabel();
        lblDisciplinaMinistrada = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblMatriculaAluno = new javax.swing.JLabel();
        lblTipoLogradouro = new javax.swing.JLabel();
        cboTipoLogradouro = new javax.swing.JComboBox<>();
        lblLogradouro = new javax.swing.JLabel();
        txtLogradouro = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        lblUf = new javax.swing.JLabel();
        cboUf = new javax.swing.JComboBox<>();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblCep = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        btnGravar = new javax.swing.JButton();
        BtnTelefones = new javax.swing.JButton();
        lblCodigoLeitor = new javax.swing.JLabel();
        txtCodigoLeitor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cboTipoLeitor = new javax.swing.JComboBox();
        txtDisciplinaMinistrada = new javax.swing.JTextField();
        txtMatriculaAluno = new javax.swing.JTextField();
        btnVoltarMenuPrincipal = new javax.swing.JButton();
        btnLimparTela = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstLeitores = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pessoas");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        lblNomeLeitor.setText("Nome:");

        lblDisciplinaMinistrada.setText("Disciplina:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lblMatriculaAluno.setText("Matricula:");

        lblTipoLogradouro.setText("Tipo Logradouro:");

        lblLogradouro.setText("Logradouro:");

        lblNumero.setText("Numero:");

        lblComplemento.setText("Complemento:");

        lblUf.setText("UF:");

        lblCidade.setText("Cidade:");

        lblBairro.setText("Bairro:");

        lblCep.setText("CEP:");

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/floppy-disk_24px.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        BtnTelefones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/telefone_24px.png"))); // NOI18N
        BtnTelefones.setText("Telefones");
        BtnTelefones.setMaximumSize(new java.awt.Dimension(105, 40));
        BtnTelefones.setMinimumSize(new java.awt.Dimension(105, 40));
        BtnTelefones.setPreferredSize(new java.awt.Dimension(105, 40));
        BtnTelefones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTelefonesActionPerformed(evt);
            }
        });

        lblCodigoLeitor.setText("Codigo:");

        jLabel1.setText("Tipo Leitor:");

        cboTipoLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoLeitorActionPerformed(evt);
            }
        });

        btnVoltarMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/undo_24px.png"))); // NOI18N
        btnVoltarMenuPrincipal.setText("Voltar");
        btnVoltarMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarMenuPrincipalActionPerformed(evt);
            }
        });

        btnLimparTela.setText("Limpar a tela");
        btnLimparTela.setMaximumSize(new java.awt.Dimension(101, 40));
        btnLimparTela.setMinimumSize(new java.awt.Dimension(101, 40));
        btnLimparTela.setPreferredSize(new java.awt.Dimension(101, 40));
        btnLimparTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparTelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 129, Short.MAX_VALUE)
                .addComponent(BtnTelefones, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCep)
                            .addComponent(lblBairro)
                            .addComponent(lblCidade)
                            .addComponent(lblUf)
                            .addComponent(lblNumero)
                            .addComponent(lblLogradouro)
                            .addComponent(lblTipoLogradouro)
                            .addComponent(lblMatriculaAluno)
                            .addComponent(lblComplemento)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDisciplinaMinistrada)
                            .addComponent(lblCodigoLeitor)
                            .addComponent(lblNomeLeitor)
                            .addComponent(jLabel1)))
                    .addComponent(btnVoltarMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtComplemento)
                            .addComponent(txtBairro)
                            .addComponent(txtCep)
                            .addComponent(txtNumero)
                            .addComponent(txtLogradouro)
                            .addComponent(txtCidade)
                            .addComponent(cboTipoLogradouro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDisciplinaMinistrada, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                        .addComponent(cboUf, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCodigoLeitor)
                                        .addComponent(cboTipoLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMatriculaAluno)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnLimparTela, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigoLeitor))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeLeitor)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboTipoLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisciplinaMinistrada)
                    .addComponent(txtDisciplinaMinistrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatriculaAluno)
                    .addComponent(txtMatriculaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoLogradouro)
                    .addComponent(cboTipoLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogradouro)
                    .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComplemento)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUf)
                    .addComponent(cboUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairro)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCep)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnTelefones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltarMenuPrincipal)
                    .addComponent(btnLimparTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        lstLeitores.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstLeitoresValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstLeitores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        // TODO add your handling code here:
        
        if(cboTipoLeitor.getSelectedItem()==TipoLeitor.Professor) {
            Endereco endereco = new Endereco((TipoLogradouro)cboTipoLogradouro.getSelectedItem(), txtLogradouro.getText(), txtNumero.getText(), txtBairro.getText(), txtCidade.getText(), (Uf)cboUf.getSelectedItem(), txtCep.getText());
            endereco.setComplemento(txtComplemento.getText());
            Professor professor = null;
            try{
                professor = new Professor(txtDisciplinaMinistrada.getText(), txtCodigoLeitor.getText(), txtNome.getText());
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            professor.setEnderecoLeitor(endereco);
            new LeitorDao().gravar(professor);
        }
        if(cboTipoLeitor.getSelectedItem()==TipoLeitor.Aluno) {
            Endereco endereco = new Endereco((TipoLogradouro)cboTipoLogradouro.getSelectedItem(), txtLogradouro.getText(), txtNumero.getText(), txtBairro.getText(), txtCidade.getText(), (Uf)cboUf.getSelectedItem(), txtCep.getText());
            endereco.setComplemento(txtComplemento.getText());
            Aluno aluno = null;
            try{
                aluno = new Aluno(txtMatriculaAluno.getText(), txtCodigoLeitor.getText(), txtNome.getText());
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            aluno.setEnderecoLeitor(endereco);
            new LeitorDao().gravar(aluno);
        }
        
        lstLeitores.setListData(new LeitorDao().getLeitores().toArray());
        
        //para limpar a tela apos cada gravacao
        txtCodigoLeitor.setText("");
        txtCep.setText("");
        txtCidade.setText("");
        txtComplemento.setText("");
        txtLogradouro.setText("");
        txtNome.setText("");
        cboTipoLeitor.setSelectedItem(TipoLeitor.Professor);
        txtNumero.setText("");
        txtBairro.setText("");
        cboUf.setSelectedItem(Uf.RJ);
        cboTipoLogradouro.setSelectedItem(TipoLogradouro.rua);
        txtNome.requestFocus();
        
    }//GEN-LAST:event_btnGravarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void lstLeitoresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstLeitoresValueChanged
        // TODO add your handling code here:
        Leitor leitor = (Leitor)lstLeitores.getSelectedValue();
        if(leitor==null) return;
        txtCodigoLeitor.setText(leitor.getCodigoLeitor());
        txtNome.setText(leitor.getNomeLeitor());
        txtCidade.setText(leitor.getEnderecoLeitor().getCidade());
        txtComplemento.setText(leitor.getEnderecoLeitor().getComplemento());
        txtLogradouro.setText(leitor.getEnderecoLeitor().getLogradouro());
        txtNumero.setText(leitor.getEnderecoLeitor().getNumero());
        txtBairro.setText(leitor.getEnderecoLeitor().getBairro());
        cboTipoLogradouro.setSelectedItem(leitor.getEnderecoLeitor().getTipoLogradouro());
        cboUf.setSelectedItem(leitor.getEnderecoLeitor().getUf());
        txtCep.setText(leitor.getEnderecoLeitor().getCep());
        if(leitor instanceof Aluno) {
            Aluno aluno = (Aluno)leitor;
            cboTipoLeitor.setSelectedItem(TipoLeitor.Aluno);
            txtMatriculaAluno.setText(aluno.getMatriculaAluno());
        } 
        else if(leitor instanceof Professor){
            Professor professor = (Professor)leitor;
            cboTipoLeitor.setSelectedItem(TipoLeitor.Professor);
            txtDisciplinaMinistrada.setText(professor.getDisciplinaMinistrada());
        }
    }//GEN-LAST:event_lstLeitoresValueChanged

    private void BtnTelefonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTelefonesActionPerformed
        // TODO add your handling code here:
        Leitor leitor = (Leitor) lstLeitores.getSelectedValue();
        if(leitor==null) {
            JOptionPane.showMessageDialog(null, "Você deve criar o leitor antes de inserir um número de telefone");
            return;
        }
        new GuiCadastroTelefone(null, true, leitor).setVisible(true);
    }//GEN-LAST:event_BtnTelefonesActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        //Colocado para que o arquivo xml seja encontrado no diretorio, ao subir a tela
        lstLeitores.setListData(new LeitorDao().getLeitores().toArray());
    }//GEN-LAST:event_formWindowActivated

    private void cboTipoLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoLeitorActionPerformed
        // TODO add your handling code here:
        if(cboTipoLeitor.getSelectedItem()==TipoLeitor.Professor) {
            lblDisciplinaMinistrada.setVisible(true);
            txtDisciplinaMinistrada.setVisible(true);
            lblMatriculaAluno.setVisible(false);
            txtMatriculaAluno.setVisible(false);
        }
        if(cboTipoLeitor.getSelectedItem()==TipoLeitor.Aluno) {
            lblDisciplinaMinistrada.setVisible(false);
            txtDisciplinaMinistrada.setVisible(false);
            lblMatriculaAluno.setVisible(true);
            txtMatriculaAluno.setVisible(true);
        }
    }//GEN-LAST:event_cboTipoLeitorActionPerformed

    private void btnVoltarMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarMenuPrincipalActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVoltarMenuPrincipalActionPerformed

    private void btnLimparTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparTelaActionPerformed
        // TODO add your handling code here:
        txtCodigoLeitor.setText("");
        txtCep.setText("");
        txtCidade.setText("");
        txtComplemento.setText("");
        txtLogradouro.setText("");
        txtNome.setText("");
        cboTipoLeitor.setSelectedItem(TipoLeitor.Professor);
        txtDisciplinaMinistrada.setText("");
        txtMatriculaAluno.setText("");
        txtNumero.setText("");
        txtBairro.setText("");
        cboUf.setSelectedItem(Uf.RJ);
        cboTipoLogradouro.setSelectedItem(TipoLogradouro.rua);
        txtNome.requestFocus();
    }//GEN-LAST:event_btnLimparTelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiCadastroLeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiCadastroLeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiCadastroLeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiCadastroLeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiCadastroLeitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTelefones;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLimparTela;
    private javax.swing.JButton btnVoltarMenuPrincipal;
    private javax.swing.JComboBox cboTipoLeitor;
    private javax.swing.JComboBox<model.TipoLogradouro> cboTipoLogradouro;
    private javax.swing.JComboBox<model.Uf> cboUf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCodigoLeitor;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblDisciplinaMinistrada;
    private javax.swing.JLabel lblLogradouro;
    private javax.swing.JLabel lblMatriculaAluno;
    private javax.swing.JLabel lblNomeLeitor;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblTipoLogradouro;
    private javax.swing.JLabel lblUf;
    private javax.swing.JList lstLeitores;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodigoLeitor;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtDisciplinaMinistrada;
    private javax.swing.JTextField txtLogradouro;
    private javax.swing.JTextField txtMatriculaAluno;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
