/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author enzoappi
 */
public class GuiModulosBiblioteca extends javax.swing.JFrame {
    private String tipoFuncionario;
    /**
     * Creates new form GuiTelaPrincipal
     */
    public GuiModulosBiblioteca(String tipoFuncionario) {
        this.tipoFuncionario = tipoFuncionario;
        initComponents();
        opcoesTela();
    }
    
    public void opcoesTela() {
        if(this.tipoFuncionario.equals("Atendente")) {
            btnCadAutores.setVisible(false);
            btnCadLivros.setVisible(false);
            btnCadLeitores.setVisible(true);
        }
        else if(this.tipoFuncionario.equals("Bibliotecario")) {
            btnCadAutores.setVisible(true);
            btnCadLivros.setVisible(true);
            btnCadLeitores.setVisible(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadAutores = new javax.swing.JButton();
        btnCadLivros = new javax.swing.JButton();
        btnCadLeitores = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnVoltarLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCadAutores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/writer.png"))); // NOI18N
        btnCadAutores.setText("Cadastro de Autores");
        btnCadAutores.setMaximumSize(new java.awt.Dimension(180, 31));
        btnCadAutores.setMinimumSize(new java.awt.Dimension(180, 31));
        btnCadAutores.setPreferredSize(new java.awt.Dimension(180, 31));
        btnCadAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadAutoresActionPerformed(evt);
            }
        });

        btnCadLivros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/book.png"))); // NOI18N
        btnCadLivros.setText("Cadastro de Livros");
        btnCadLivros.setMaximumSize(new java.awt.Dimension(180, 31));
        btnCadLivros.setMinimumSize(new java.awt.Dimension(180, 31));
        btnCadLivros.setPreferredSize(new java.awt.Dimension(180, 31));
        btnCadLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadLivrosActionPerformed(evt);
            }
        });

        btnCadLeitores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/reader.png"))); // NOI18N
        btnCadLeitores.setText("Cadastro de Leitores");
        btnCadLeitores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadLeitoresActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("SBF - SISTEMA DA BIBLIOTECA FEMASS");

        btnVoltarLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/undo_16px.png"))); // NOI18N
        btnVoltarLogin.setText("Voltar");
        btnVoltarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnCadLeitores, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltarLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadLeitores, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltarLogin)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadAutoresActionPerformed
        // TODO add your handling code here:
        new GuiCadastroAutor().setVisible(true);
    }//GEN-LAST:event_btnCadAutoresActionPerformed

    private void btnCadLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadLivrosActionPerformed
        // TODO add your handling code here:
        new GuiCadastroLivro().setVisible(true);
    }//GEN-LAST:event_btnCadLivrosActionPerformed

    private void btnCadLeitoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadLeitoresActionPerformed
        // TODO add your handling code here:
        new GuiCadastroLeitor().setVisible(true);
    }//GEN-LAST:event_btnCadLeitoresActionPerformed

    private void btnVoltarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarLoginActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVoltarLoginActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GuiModulosBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GuiModulosBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GuiModulosBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GuiModulosBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GuiModulosBiblioteca().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadAutores;
    private javax.swing.JButton btnCadLeitores;
    private javax.swing.JButton btnCadLivros;
    private javax.swing.JButton btnVoltarLogin;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
