/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.AutorDao;
import dao.LivroDao;
import javax.swing.JOptionPane;
import model.Livro;
import model.Autor;

/**
 *
 * @author enzoappi
 */
public class GuiSelecaoAutorLivro extends javax.swing.JDialog {
    private Livro livro;
    
    /**
     * Creates new form GuiEmail
     */
    public GuiSelecaoAutorLivro(java.awt.Frame parent, boolean modal, Livro livro) {
        super(parent, modal);
        initComponents();
        this.livro = livro;
        lstAutoresBD.setListData(new AutorDao().getAutores().toArray());
        lstAutoresSelecionados.setListData(this.livro.getAutores().toArray());
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstAutoresBD = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeAutor = new javax.swing.JTextField();
        btnSelecionar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCodAutor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNacAutor = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstAutoresSelecionados = new javax.swing.JList();
        lblAutoresSelecionados = new javax.swing.JLabel();
        btnVoltarMenuCadLivro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SELEÇÃO DOS AUTORES DOS LIVROS");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        lstAutoresBD.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lstAutoresBD.setMinimumSize(new java.awt.Dimension(100, 70));
        lstAutoresBD.setName(""); // NOI18N
        lstAutoresBD.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstAutoresBDValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstAutoresBD);

        getContentPane().add(jScrollPane1);

        jLabel1.setText("Codigo");

        txtNomeAutor.setEditable(false);

        btnSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/toque_16px.png"))); // NOI18N
        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        txtCodAutor.setEditable(false);

        jLabel3.setText("Nacionalidade");

        txtNacAutor.setEditable(false);

        lstAutoresSelecionados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(lstAutoresSelecionados);

        lblAutoresSelecionados.setText("Autores selecionados");

        btnVoltarMenuCadLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/undo_16px.png"))); // NOI18N
        btnVoltarMenuCadLivro.setText("Voltar");
        btnVoltarMenuCadLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarMenuCadLivroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(lblAutoresSelecionados)
                        .addGap(0, 69, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnVoltarMenuCadLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNomeAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                        .addComponent(txtNacAutor)
                                        .addComponent(txtCodAutor))
                                    .addComponent(btnSelecionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNacAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelecionar)
                    .addComponent(btnVoltarMenuCadLivro))
                .addGap(29, 29, 29)
                .addComponent(lblAutoresSelecionados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstAutoresBDValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstAutoresBDValueChanged
        // TODO add your handling code here:
        Autor autor = (Autor) lstAutoresBD.getSelectedValue();
        txtCodAutor.setText(autor.getCodigoAutor());
        txtNomeAutor.setText(autor.getNomeAutor());
        txtNacAutor.setText(autor.getNacionalidadeAutor());
    }//GEN-LAST:event_lstAutoresBDValueChanged

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        // TODO add your handling code here:
        Autor autor = (Autor) lstAutoresBD.getSelectedValue();
        if(autor == null) {
            JOptionPane.showMessageDialog(null, "Você deve escolher um autor da lista para adicionar");
            return;
        }
        this.livro.adicionarAutor(autor);
        new LivroDao().salvar();
        txtCodAutor.setText("");
        txtNomeAutor.setText("");
        txtNacAutor.setText("");
        txtNomeAutor.requestFocus();
        lstAutoresSelecionados.setListData(this.livro.getAutores().toArray());
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void btnVoltarMenuCadLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarMenuCadLivroActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVoltarMenuCadLivroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JButton btnVoltarMenuCadLivro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAutoresSelecionados;
    private javax.swing.JList lstAutoresBD;
    private javax.swing.JList lstAutoresSelecionados;
    private javax.swing.JTextField txtCodAutor;
    private javax.swing.JTextField txtNacAutor;
    private javax.swing.JTextField txtNomeAutor;
    // End of variables declaration//GEN-END:variables
}
